[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"


[project]
name = "imdbinfo"
version = "0.2.6"
description = "A Python service for querying IMDb data"
readme = "README.md"
license = { file = "LICENSE.txt" }
authors = [
    { name = "@tveronesi", email = "you@example.com" }
]
dependencies = [
    "requests",
    "lxml",
    "pydantic"
]

keywords = [
    "imdb",
    "movie",
    "tv",
    "series",
    "information",
    "data"
]

classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",

]

[tool.setuptools]
packages = ["imdbinfo"]

[tool.setuptools.package-data]
"sample_json_source" = ["*"]
