name: Build and Create GitHub Release

on:
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python-version: [3.7, 3.10]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip
          pip install build

      - name: Build package
        run: python -m build

      - name: Extract Changelog Entry
        id: changelog
        run: |
          VERSION=${GITHUB_REF##*/v}
          ENTRY=$(awk "/^##? v$VERSION/{flag=1;next}/^##? /{flag=0}flag" CHANGELOG.md | sed '/^$/d')
          echo "CHANGELOG<<EOF" >> $GITHUB_ENV
          echo "$ENTRY" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: ${{ env.CHANGELOG }}
